### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by gufoe** [kylepaulsen/kbm-robot#4]
Hi, I'm having this error after ~790 chars have been typed (both java 6 and java 7):

```
$ node test.js 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at Pipe.onread (net.js:544:26)
jake@levix:/tmp$ node test.js 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at Pipe.onread (net.js:544:26)
```

The code is:

``` javascript
var robot = require("kbm-robot");

robot.startJar('7');

msg = 'Aesop was one of the great Greek writers. He is best known for his fables, stories that have a moral. They teach us something about how we should live our lives. Aesop wrote thousands of these stories. Here are a few.\nThe Wolf in Sheep\'s Clothing\nOnce upon a time, a Wolf decided to disguise the way he looked. He thought it would help him get food more easily. He put on the skin of a sheep, then he went out with the flock into the pasture. Even the shepherd was fooled by his clever costume. In the evening, the shepherd put him in with the rest of the sheep. He closed the gate and made sure it was secure before he went to bed. In the middle of the night, he came back to the fold to get some meat for the next day. Instead of a sheep, though, he grabbed the Wolf, killing him instantly.\nThose who look to harm others will be harmed themselves.\nThe Bat and the Weasel\nA Bat fell on the ground and was caught by a Weasel. It begged the Weasel to spare its life, but the Weasel refused. It told the Bat that birds, by nature, were its enemy. The Bat assured him that it was not a bird, it was a mouse. The Weasel thought a moment, then set it free. A while later, the Bat fell again to the ground, and it was caught by another Weasel. It begged this Weasel not to eat him, either. The Weasel, though, said it did not like mice at all and would eat it. The Bat told the Weasel that it was not a mouse, but a bat. The second Weasel had no good answer, so he let it go.\nThe Bat knew it is always wise to turn events to your advantage.\nThe Lion and the Mouse\nA sleeping Lion was woken up by a Mouse running over his face. He got up angrily and caught the scared little Mouse. He was about to kill the Mouse, but it said in its squeaky little voice, "If you would only spare my life, I would be sure to repay your kindness." The Lion laughed at such nonsense, but he let him go. A short time later, though, the Lion was caught by some hunters. They bound him by ropes to the ground. The Mouse recognized his roar, and he rushed over and gnawed the rope with his teeth, setting the Lion free. The Mouse said "You laughed at the idea of my ever being able to help you. Now you know that it is possible for even a small little Mouse to help a great big Lion."'

robot.sleep(1000)
    .typeString(msg)
    .go()
    .then(robot.stopJar);

```

I'm on Debian unstable:

```
$ node -v
v4.2.4
```

A possible workaround is to split the sentence in chunks and rebooting the robot, calling both `robot.stopJar()` followed by a `robot.startJar()`:

``` javascript
var robot = require("kbm-robot");


msg = 'Aesop was one of the great Greek writers. He is best known for his fables, stories that have a moral. They teach us something about how we should live our lives. Aesop wrote thousands of these stories. Here are a few.\nThe Wolf in Sheep\'s Clothing\nOnce upon a time, a Wolf decided to disguise the way he looked. He thought it would help him get food more easily. He put on the skin of a sheep, then he went out with the flock into the pasture. Even the shepherd was fooled by his clever costume. In the evening, the shepherd put him in with the rest of the sheep. He closed the gate and made sure it was secure before he went to bed. In the middle of the night, he came back to the fold to get some meat for the next day. Instead of a sheep, though, he grabbed the Wolf, killing him instantly.\nThose who look to harm others will be harmed themselves.\nThe Bat and the Weasel\nA Bat fell on the ground and was caught by a Weasel. It begged the Weasel to spare its life, but the Weasel refused. It told the Bat that birds, by nature, were its enemy. The Bat assured him that it was not a bird, it was a mouse. The Weasel thought a moment, then set it free. A while later, the Bat fell again to the ground, and it was caught by another Weasel. It begged this Weasel not to eat him, either. The Weasel, though, said it did not like mice at all and would eat it. The Bat told the Weasel that it was not a mouse, but a bat. The second Weasel had no good answer, so he let it go.\nThe Bat knew it is always wise to turn events to your advantage.\nThe Lion and the Mouse\nA sleeping Lion was woken up by a Mouse running over his face. He got up angrily and caught the scared little Mouse. He was about to kill the Mouse, but it said in its squeaky little voice, "If you would only spare my life, I would be sure to repay your kindness." The Lion laughed at such nonsense, but he let him go. A short time later, though, the Lion was caught by some hunters. They bound him by ropes to the ground. The Mouse recognized his roar, and he rushed over and gnawed the rope with his teeth, setting the Lion free. The Mouse said "You laughed at the idea of my ever being able to help you. Now you know that it is possible for even a small little Mouse to help a great big Lion."'



function type() {
    robot.stopJar();

    if (i == chunks.length)
        return;

    robot.startJar();
    robot
        .sleep(i == 0 ? 1000 : 1)
        .typeString(chunks[i]+'\n', 0, 0)
        .go()
        .then(type);
    i++;
}

var i = 0;
chunks = msg.split('\n')
robot.startJar();
type();

```

**Comment by kylepaulsen** [comment]
Thanks for reporting. I confirmed this on Ubuntu 14.04. Strangely enough, this doesn't seem to happen on Windows - if I try to output in sublime, it crashes though... notepad works fine however.
It definitely seems like there is some hard limit depending on your system. In my case, it always stopped typing after 883 characters. The speed at which the characters were typed didn't matter.
This seems like a tough one. I'll look into it more soon.

**Comment by kylepaulsen** [comment]
OK while debugging, I think I accidentally fixed it. I just added stdio event listeners: 3fc59ad7bea9033ce68c6b9a5088d8e313272f50
Maybe without those, some buffer somewhere overflows. I don't really know.

Can you update to kbm-robot@0.0.4 and see if the fix works for you?

**Comment by gufoe** [comment]
It's perfect, it works now, great job!
