### ISSUE TITLE
Not able to run sample code

### ISSUE THREAD

**Issue by pd-vt** [kylepaulsen/kbm-robot#7]
I have installed npm package and trying to run basic demo code given in readme file. However, while executing this project with Node V12.18.0 getting error as per below. 

> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn java ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn java',
>   path: 'java',
>   spawnargs: [
>     '-jar',
>     'C:\\Users\\admin\\Desktop\\key\\node_modules\\kbm-robot\\java\\robot7.jar'
>   ]
> }

And when try running code with Node V10.23.0 getting error as per below. 

> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn java ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
>     at onErrorNT (internal/child_process.js:415:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> Emitted 'error' event at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
>     at onErrorNT (internal/child_process.js:415:16)
>     [... lines matching original stack trace ...]
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by OlympicAngel** [comment]
make sure you got java installed (as it ueses it)

**Comment by sharmavinay747** [comment]
![image](https://user-images.githubusercontent.com/25406800/116693121-13336780-a9db-11eb-8769-c14f10dabbde.png)


FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap o
